name: Maravel

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
  workflow_dispatch:

jobs:
  maravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - name: Install Dependencies
      working-directory: ../../
      run: composer install --no-cache --no-interaction --prefer-dist --no-progress --optimize-autoloader
    - name: Execute tests
      working-directory: ../../
      run: vendor/bin/phpunit
